# Generated by Django 6.0.7 on 2026-07-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="psedonimo",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
